swagger: '2.0'
info:
  description: >-
    Payload model example
  version: 0.1.0
  title: Payload example
  contact:
    email: some@example.com
  x-hugo-values:
    tags:
      - payload
    public: true
definitions:
  Payload:
    description: >-
      Payload model example
    type: object
    properties:
      name:
        type: string
        description: user name
      email:
        type: number
        example: user@example.com
        description: user email